# Generated by Django 5.1.3 on 2024-12-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatright', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='useraction',
            constraint=models.UniqueConstraint(fields=('userid', 'dishname'), name='unique_user_dish'),
        ),
    ]
