# Generated by Django 5.1.3 on 2024-12-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatright', '0002_useraction_unique_user_dish'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useraction',
            name='unique_user_dish',
        ),
    ]
