# Generated by Django 5.1.3 on 2024-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatright', '0004_userfavoritedishes_useraction_unique_user_dish_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfavoritedishes',
            constraint=models.UniqueConstraint(fields=('userid', 'dishname'), name='unique_fav_dish'),
        ),
    ]
